name: Build Conda Package Linux

on: [ push ]

env:
  NAME_OF_PACKAGE: katbeam


jobs:
  build_and_upload:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
      - name: Install Conda Build
        run: |
          conda install conda-build
          conda install anaconda
      - name: Build conda
        run: |
          cd conda/
          conda build -c i4ds -c conda-forge .
      - name: Publish to Conda Linux
        shell: bash -l {0}
        run: |
          conda activate base
          anaconda -t ${{ secrets.ANACONDA_SECRET }} upload /usr/share/miniconda/conda-bld/linux-64/{{env.NAME_OF_PACKAGE}}*.tar.bz2
  install_and_test:
    needs: build_and_upload
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
      - name: Install Package
        shell: bash -l {0}
        run: |
          conda activate base
          conda config --append channels conda-forge
          conda install -c i4ds {{env.NAME_OF_PACKAGE}}
